# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PeerReview03CurrencyConverter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PeerReview03CurrencyConverter
pod 'CurrencyRequest' , '~> 0.1'


end
