# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PeerReview04DistanceCalculation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PeerReview04DistanceCalculation

pod 'DistanceGetter', '~> 0.1'

end
